### ISSUE TITLE
The -d switch doesn't work

### ISSUE THREAD

**Issue by mitm001** [peter-evans/link-checker#28]
Trying to use the -d switch like so;

```
args: -d jme-wiki/docs -x ^(.*)(M|m)(.*)(E|e)(ngine/wiki)(/edit/master.*)?$ -v -r -c 32 *
```
yet the out.md shows that its always checking from the root of repository, i.e shows the LICENSE, README.md, the out.md, every folder gets checked.

Maybe I am not interpreting the use of the switch properly?

-d, --document-root <directory>  Set document root directory for absolute paths.

To me this says set the directory to search from but it is searching folders above it, including root. There is no way to pass any arguments to the action itself to select the proper directory so this -d switch is the only option unless you know of some other way to do it, outside of setting the working-directory on a job level.

**Comment by peter-evans** [comment]
@mitm001 If you want to search only in `jme-wiki/docs`, I think the arguments you want are `-v -r jme-wiki/docs`. Currently, the final `*` at the end of the args means search everything at the root. The `-d` flag is for a different purpose.

**Comment by mitm001** [comment]
Ahh, ok, I mistook the `*` as a terminating character for the args string. Newbie mistake. 

Thank you.
