### ISSUE TITLE
Getting "Too Many Requests (HTTP error 429)" Error in the "out.md" File

### ISSUE THREAD

**Issue by praneesha** [peter-evans/link-checker#33]
@peter-evans - Need your kind help once again.

I am getting this "Too Many Requests (HTTP error 429)" Error in the `out.md` file when calling to external sites as shown below.

Is there a way to get this resolved or to skip displaying these in the `out.md` file?

<img width="958" alt="Screenshot 2020-11-02 at 20 33 50" src="https://user-images.githubusercontent.com/11707273/97883371-c8e26e00-1d4a-11eb-95c4-2d411a4c3548.png">

**Comment by peter-evans** [comment]
@praneesha We already have an open issue for discussion about this [here](https://github.com/peter-evans/link-checker/issues/29) so I'm going to close this.

To answer your question quickly though, I don't know a way to skip these errors in the output.
