### ISSUE TITLE
Adding a Config JSON File

### ISSUE THREAD

**Issue by praneesha** [peter-evans/link-checker#34]
@peter-evans - Is there a way that I can add a config.json file and add it to the link checker?

I want to define the required 429 retry options and give the `-a` and `-r` arguments as per https://github.com/tcort/markdown-link-check#markdownlinkcheckmarkdown-opts-callback.

**Comment by peter-evans** [comment]
Hi @praneesha 

This action is a wrapper around the tool [Liche](https://github.com/raviqqe/liche). What you linked to seems to be a different tool that also does link checking of markdown documents. I'm afraid this action doesn't support that tool.
