### ISSUE TITLE
Small read buffer

### ISSUE THREAD

**Issue by irongut** [peter-evans/link-checker#37]
I've been having an issue recently with the LinkChecker being unable to check some links. All the links are to discord.gg and the errors are like the below:

```
ERROR	https://discord.gg/0g95XxxKRcw7ypJZ
Error when reading response headers: small read buffer. Increase ReadBufferSize. Buffer size=4096, contents: "HTTP/1.1 200 OK\r\nDate: Sun, 13 Dec 2020 01:47:32 GMT\r\nContent-Type: text/html\r\nContent-Length: 5470\r\nConnection: close\r\nSet-Cookie: __cfduid=d7b69115ea34f9523c2f3fe70066c7f4f1607824052; expires=Tue, 1"..."UTKYEGSvaOPAuH6BsXOw%2BzPXlC2mg%3D%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}\r\nNel: {\"report_to\":\"cf-nel\",\"max_age\":604800}\r\nServer: cloudflare\r\nAlt-Svc: h3-27=\":443\"; ma=86400, h3-28=\":443\"; ma=86400, "
```

I don't see an arg to increase the read buffer, do you know of a solution?

**Comment by peter-evans** [comment]
Hi @irongut 

This action is a wrapper around the tool, [Liche](https://github.com/raviqqe/liche), so this kind of issue should be directed there. However, Liche has recently been deprecated so the owner most likely will not be releasing any further patches. I'm looking into options to release a new version of this action based on a different tool.

**Comment by peter-evans** [comment]
I've decided to deprecate this action in favour of [lychee-action](https://github.com/lycheeverse/lychee-action), which is a fork of this project based on [lychee](https://github.com/lycheeverse/lychee). Please consider using that action. Hopefully, that project will be able to solve your issue.

**Comment by irongut** [comment]
@peter-evans Thanks for the help and your action, which was great until this issue. I'll look into lychee-action as an alternative.
